### ISSUE TITLE
Simple sketch doesnt work

### ISSUE THREAD

**Issue by nodoubtman** [brunojoyal/PushoverESP32#2]
Hello, simple notification without image doesnt work, however with the image it does works:

`#include <FS.h>
#include "SPIFFS.h"

#define TITRE_PROGRAMME "ESP32_TEST"

const char *ssid          = "ssid";
const char *password  = "password";

// https://github.com/brunojoyal/PushoverESP32
#include <PushoverESP32.h>
Pushover pushoverClientImage("xxx", "yyyy", &SPIFFS);
Pushover pushoverClient("xxx", "yyy");
const char* MON_IMAGE = "/mailbox.jpg";

void SendPushOverMarcWithAttach(const char* titre, const char* msg, const char* sound, const char* img_as_attachment) {
  PushoverMessage myMessage;

  myMessage.title   = titre;
  myMessage.message = msg;
  myMessage.sound   = sound;

  File photo = SPIFFS.open(img_as_attachment);
  myMessage.attachment = &photo;
  pushoverClientImage.send(myMessage);
}

void SendPushOverMarc(const char* titre, const char* msg, const char* sound) {
  PushoverMessage myMessage;

  myMessage.title   = titre;
  myMessage.message = msg;
  myMessage.sound   = sound;

  pushoverClient.send(myMessage);
}

void Connect_WiFi() {
  WiFi.disconnect();
  Serial.println( F("\nConnecting to WiFi...") );
  WiFi.begin(ssid, password);
  while (WiFi.status() != WL_CONNECTED) {
    Serial.print( F(".") );
    delay(500);
  }
  Serial.println("\nWiFi at: " + WiFi.localIP().toString());
}

// setup
void setup() {
  Serial.begin(115200);
  Serial.println();

  bool spiffsOK = SPIFFS.begin();
  Serial.println(spiffsOK ? F("SPIFFS OK") : F("SPIFFS FAILED!!") );

  Connect_WiFi();
  delay(1000);

  char bufferMsg[25];
  sprintf(bufferMsg, "http://%s/", WiFi.localIP().toString().c_str());
  Serial.printf("\nbufferMsg: %s\n", bufferMsg);
  SendPushOverMarc(TITRE_PROGRAMME, bufferMsg, "magic");
}

// loop
void loop() {
  // ...
}`

**Comment by nodoubtman** [comment]
Ok

**Comment by kongenafbrovejen** [comment]
I have got the same issue - works brilliant with attachted file ...

**Comment by giusmos** [comment]
I have the same issue, when I print the output of "pushoverClient.send" with the function below I get response 400 and do not receive any message on my Pushover app.

Serial.println(pushoverClient.send(myMessage));

**Comment by nodoubtman** [comment]
Hello, I have modified the 

int Pushover::send(PushoverMessage newMessage)

function:

replace this function with this one:

`int Pushover::send(PushoverMessage newMessage)
{
  int responseCode = 0;
  std::map<const char *, const char *> messageData;
  messageData["token"] = _token;
  messageData["user"] = _user;
  messageData["message"] = newMessage.message;
  messageData["title"] = newMessage.title;
  messageData["url"] = newMessage.url;
  messageData["url_title"] = newMessage.url_title;
  messageData["html"] = newMessage.html ? "1" : "0";

  char bufTimeStamp[15];
  snprintf( bufTimeStamp, sizeof(bufTimeStamp), "%d", newMessage.timestamp );

  char bufPriority[3];
  snprintf( bufPriority, sizeof(bufPriority), "%d", newMessage.priority );
  messageData["timestamp"] = bufTimeStamp;
  messageData["priority"]  = bufPriority;

  messageData["sound"] = newMessage.sound;
  // No attachment, so just a regular HTTPS POST request.
  if (!newMessage.attachment)
  {
    Serial.println( F("NO ATTACHMENT") );
    HTTPClient myClient;
    myClient.begin(PUSHOVER_API_URL, PUSHOVER_ROOT_CA);
    myClient.addHeader( F("Content-Type"), F("application/json") );
    StaticJsonDocument<512> doc;
    std::map<const char *, const char *>::iterator it = messageData.begin();
    while (it != messageData.end()) {
      doc[it->first] = it->second;
      it++;
    }

    char output[512];
    serializeJson(doc, output);
    serializeJsonPretty(doc, Serial);
    responseCode = myClient.POST(output);

    myClient.end();
  }
  else // attachment, so we enter multipart/form-data hell...
  {
    MultipartMessage message;
    message.file = newMessage.attachment;
    message.otherData = messageData;
    message.contentType = "image/jpeg";
    message.name = "attachment";
    message.filename = "image";
    pushoverUploader.send(message);
  }
  return responseCode;
}
`

Thanks.
Marc.

**Comment by nodoubtman** [comment]
> Hello, I have modified the
> 
> int Pushover::send(PushoverMessage newMessage)
> 
> function:
> 
> replace this function with this one:
> 
> `int Pushover::send(PushoverMessage newMessage) { int responseCode = 0; std::map<const char *, const char *> messageData; messageData["token"] = _token; messageData["user"] = _user; messageData["message"] = newMessage.message; messageData["title"] = newMessage.title; messageData["url"] = newMessage.url; messageData["url_title"] = newMessage.url_title; messageData["html"] = newMessage.html ? "1" : "0";
> 
> char bufTimeStamp[15]; snprintf( bufTimeStamp, sizeof(bufTimeStamp), "%d", newMessage.timestamp );
> 
> char bufPriority[3]; snprintf( bufPriority, sizeof(bufPriority), "%d", newMessage.priority ); messageData["timestamp"] = bufTimeStamp; messageData["priority"] = bufPriority;
> 
> messageData["sound"] = newMessage.sound; // No attachment, so just a regular HTTPS POST request. if (!newMessage.attachment) { Serial.println( F("NO ATTACHMENT") ); HTTPClient myClient; myClient.begin(PUSHOVER_API_URL, PUSHOVER_ROOT_CA); myClient.addHeader( F("Content-Type"), F("application/json") ); StaticJsonDocument<512> doc; std::map<const char *, const char *>::iterator it = messageData.begin(); while (it != messageData.end()) { doc[it->first] = it->second; it++; }
> 
> ```
> char output[512];
> serializeJson(doc, output);
> serializeJsonPretty(doc, Serial);
> responseCode = myClient.POST(output);
> 
> myClient.end();
> ```
> 
> } else // attachment, so we enter multipart/form-data hell... { MultipartMessage message; message.file = newMessage.attachment; message.otherData = messageData; message.contentType = "image/jpeg"; message.name = "attachment"; message.filename = "image"; pushoverUploader.send(message); } return responseCode; } `
> 
> Thanks. Marc.


The main bug was in timestamp String, and priority it was returning:
NO ATTACHMENT
{
  "token": "azfdwbt2pimejsescfyqh6st2wgvf9",
  "url": "",
  "url_title": "",
  "html": "0",
  "priority": "(%⸮?(%⸮?⸮&⸮?('⸮?",
  "sound": "magic",
  "timestamp": "(%⸮?(%⸮?⸮&⸮?('⸮?",
  "message": "http://192.168.0.100/",
  "title": "ESP32_TEST",
  "user": "uab69xwpxj1pzpfc8gcwjmu64m2rc9"
}

so the new code is working.
Just try the new code.

Marc.

**Comment by nodoubtman** [comment]
Hello, I have modified the

    int Pushover::send(PushoverMessage newMessage)

    function:

    replace this function with this one:

    `int Pushover::send(PushoverMessage newMessage) { int responseCode = 0; std::map<const char *, const char *> messageData; messageData["token"] = _token; messageData["user"] = _user; messageData["message"] = newMessage.message; messageData["title"] = newMessage.title; messageData["url"] = newMessage.url; messageData["url_title"] = newMessage.url_title; messageData["html"] = newMessage.html ? "1" : "0";

    char bufTimeStamp[15]; snprintf( bufTimeStamp, sizeof(bufTimeStamp), "%d", newMessage.timestamp );

    char bufPriority[3]; snprintf( bufPriority, sizeof(bufPriority), "%d", newMessage.priority ); messageData["timestamp"] = bufTimeStamp; messageData["priority"] = bufPriority;

    messageData["sound"] = newMessage.sound; // No attachment, so just a regular HTTPS POST request. if (!newMessage.attachment) { Serial.println( F("NO ATTACHMENT") ); HTTPClient myClient; myClient.begin(PUSHOVER_API_URL, PUSHOVER_ROOT_CA); myClient.addHeader( F("Content-Type"), F("application/json") ); StaticJsonDocument<512> doc; std::map<const char *, const char *>::iterator it = messageData.begin(); while (it != messageData.end()) { doc[it->first] = it->second; it++; }

    char output[512];
    serializeJson(doc, output);
    serializeJsonPretty(doc, Serial);
    responseCode = myClient.POST(output);

    myClient.end();

    } else // attachment, so we enter multipart/form-data hell... { MultipartMessage message; message.file = newMessage.attachment; message.otherData = messageData; message.contentType = "image/jpeg"; message.name = "attachment"; message.filename = "image"; pushoverUploader.send(message); } return responseCode; } `

    Thanks. Marc.

The main bug was in timestamp String, and priority it was returning:
NO ATTACHMENT
{
"token": "azfdwbt2pimejsescfyqh6st2wgvf9",
"url": "",
"url_title": "",
"html": "0",
"priority": "(%⸮?(%⸮?⸮&⸮?('⸮?",
"sound": "magic",
"timestamp": "(%⸮?(%⸮?⸮&⸮?('⸮?",
"message": "http://192.168.0.100/",
"title": "ESP32_TEST",
"user": "uab69xwpxj1pzpfc8gcwjmu64m2rc9"
}

so the new code is working.
Just try the new code.

Marc.

**Comment by nodoubtman** [comment]
Hello, I have modified the

int Pushover::send(PushoverMessage newMessage)

function:

replace this function with this one:

`int Pushover::send(PushoverMessage newMessage)
{
int responseCode = 0;
std::map<const char *, const char *> messageData;
messageData["token"] = _token;
messageData["user"] = _user;
messageData["message"] = newMessage.message;
messageData["title"] = newMessage.title;
messageData["url"] = newMessage.url;
messageData["url_title"] = newMessage.url_title;
messageData["html"] = newMessage.html ? "1" : "0";

char bufTimeStamp[15];
snprintf( bufTimeStamp, sizeof(bufTimeStamp), "%d", newMessage.timestamp );

char bufPriority[3];
snprintf( bufPriority, sizeof(bufPriority), "%d", newMessage.priority );
messageData["timestamp"] = bufTimeStamp;
messageData["priority"] = bufPriority;

messageData["sound"] = newMessage.sound;
// No attachment, so just a regular HTTPS POST request.
if (!newMessage.attachment)
{
Serial.println( F("NO ATTACHMENT") );
HTTPClient myClient;
myClient.begin(PUSHOVER_API_URL, PUSHOVER_ROOT_CA);
myClient.addHeader( F("Content-Type"), F("application/json") );
StaticJsonDocument<512> doc;
std::map<const char *, const char *>::iterator it = messageData.begin();
while (it != messageData.end()) {
doc[it->first] = it->second;
it++;
}

char output[512];
serializeJson(doc, output);
serializeJsonPretty(doc, Serial);
responseCode = myClient.POST(output);

myClient.end();

}
else // attachment, so we enter multipart/form-data hell...
{
MultipartMessage message;
message.file = newMessage.attachment;
message.otherData = messageData;
message.contentType = "image/jpeg";
message.name = "attachment";
message.filename = "image";
pushoverUploader.send(message);
}
return responseCode;
}
`

Thanks.
Marc.
